videos:
  - title: 'ROR Workshop: 18 - Refactoring Code'
    link: 'https://www.youtube.com/watch?v=0iImjqzEBkk'
    tags: 'refactoring, ruby'
    description: 'Video description'
  - title: 'ROR Workshop: SSO-Devise and OmniAuth'
    link: 'https://www.youtube.com/watch?v=uYFkSsmuZuw'
    tags: 'sso, devise, omniauth'
    description: 'Video description'
  - title: 'RoR Worshop 12: Active Record When yes and no'
    link: 'https://www.youtube.com/watch?v=dc9ytssus0k'
    tags: 'active, record, rails'
    description: 'Video description'
  - title: 'ROR Workshop: 16 - Build Gems'
    link: 'https://www.youtube.com/watch?v=Rm8Jp7VqZTU'
    tags: 'build, gems, engines'
    description: 'Video description'
  - title: 'RoR Worshop 13: RVM: Ruby Virtual Machine'
    link: 'https://www.youtube.com/watch?v=MF2U3K25qdQ'
    tags: 'rvm'
    description: 'Video description'
  - title: 'RoR Workshop 11: SOLID (object oriented design)'
    link: 'https://www.youtube.com/watch?v=LZHLH7cWAmM'
    tags: 'solid, object, oriented, design'
    description: 'Video description'
  - title: 'RoR Workshop 1: Static Code Analizers in Rails'
    link: 'https://www.youtube.com/watch?v=QyoexmPxBGw'
    tags: 'static, code, analizers'
    description: 'Video description'
  - title: 'A Test Video'
    link: 'https://www.youtube.com/watch?v=u3mw8IaWFSQ'
    tags: 'drg, test, rails'
    description: 'Video description'
